### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SecretaryBirds** [tocinc/rmw_coredx#4]
There are some Linux-specific time function calls that prohibit operability on Windows and potentially OSX. (I'm not sure on OSX since I didn't test it.)

    struct timespec now;
    clock_gettime(CLOCK_REALTIME, &now);

stl has a good time library which should provide a bit more os-independence. It's the std::chrono library.

**Comment by SecretaryBirds** [comment]
so the clock_gettime is peppered throughout the functions.hpp, but they are all captured in #ifdef DEBUG statements.
There is one instance of clock_gettime in the functions.cpp, but it doesn't seem to have any purpose.

**Comment by ClarkTucker** [comment]
Yep, it looks like the clock_gettime() call in functions.cpp was dangling debug code... safe to remove.
I've pushed a fix for that.

We still haven't set up a Windows build env for ROS2 yet, so we're happy to hear about any Windows build issues you find [or any others, for that matter].

**Comment by SecretaryBirds** [comment]
Currently getting a new error on linking.

"C:\Asi\master\ros2\build\rmw_coredx_cpp\rmw_coredx_cpp.sln" (default target) (1) ->
       "C:\Asi\master\ros2\build\rmw_coredx_cpp\rmw_coredx_cpp.vcxproj.metaproj" (default target) (3) ->
       "C:\Asi\master\ros2\build\rmw_coredx_cpp\rmw_coredx_cpp.vcxproj" (default target) (5) ->
       (Link target) ->
         functions.obj : error LNK2019: unresolved external symbol "class DDS::DomainParticipantQos const DDS::PARTICIPANT_QOS_DEFAULT" (?PARTICIPANT_QOS_DEFAULT@DDS@@3VDomainParticipantQos@1@B) referenced in function "struct rmw_node_t
        * __cdecl rmw_create_node(char const *,unsigned __int64)" (?rmw_create_node@@YAPEAUrmw_node_t@@PEBD_K@Z) [C:\Asi\master\ros2\build\rmw_coredx_cpp\rmw_coredx_cpp.vcxproj]
         functions.obj : error LNK2019: unresolved external symbol "class DDS::PublisherQos const DDS::PUBLISHER_QOS_DEFAULT" (?PUBLISHER_QOS_DEFAULT@DDS@@3VPublisherQos@1@B) referenced in function "bool __cdecl get_datawriter_qos(class
        DDS::DomainParticipant *,struct rmw_qos_profile_t const *,class DDS::DataWriterQos &)" (?get_datawriter_qos@@YA_NPEAVDomainParticipant@DDS@@PEBUrmw_qos_profile_t@@AEAVDataWriterQos@2@@Z) [C:\Asi\master\ros2\build\rmw_coredx_cpp\
       rmw_coredx_cpp.vcxproj]
         functions.obj : error LNK2019: unresolved external symbol "class DDS::SubscriberQos const DDS::SUBSCRIBER_QOS_DEFAULT" (?SUBSCRIBER_QOS_DEFAULT@DDS@@3VSubscriberQos@1@B) referenced in function "bool __cdecl get_datareader_qos(c
       lass DDS::DomainParticipant *,struct rmw_qos_profile_t const *,class DDS::DataReaderQos &)" (?get_datareader_qos@@YA_NPEAVDomainParticipant@DDS@@PEBUrmw_qos_profile_t@@AEAVDataReaderQos@2@@Z) [C:\Asi\master\ros2\build\rmw_coredx_
       cpp\rmw_coredx_cpp.vcxproj]
         C:\Asi\master\ros2\build\rmw_coredx_cpp\Release\rmw_coredx_cpp.dll : fatal error LNK1120: 3 unresolved externals [C:\Asi\master\ros2\build\rmw_coredx_cpp\rmw_coredx_cpp.vcxproj]

**Comment by SecretaryBirds** [comment]
I am using a new build of 4.0.13 built for VS 2015, but it still isn't linking properly. I'm not sure what's going on.

**Comment by ClarkTucker** [comment]
Are you able to share the full link command?  Are you linking with CoreDX DDS libraries statically or dynamically?  To support dynamic linking (eg, against a DLL), you'll need to, at least, add **/DCOREDX_DLL** to the compile lines.  And, that may not be sufficient: for example, if the generated typesupport code is linked into a DLL, then it will need some special compile flags as well.   

I'm not sure this is the source of your errors, but it could be. I'll be able to verify once we have a Windows build env set up for ROS.

**Comment by SecretaryBirds** [comment]
Yes, I believe ROS2 tries to dynamically link everything by default.

**Comment by SecretaryBirds** [comment]
Manually adding /DCOREDX to the compile line in the .sln file made it compile successfully.
So adding it to the Cmake file for windows VS solution files might be the way to go? Thoughts?

**Comment by SecretaryBirds** [comment]
Run into another issue on the 'builtin_interfaces' package. When attempting to perform the idl generation, it was throwing an error

    coredx_cpp is an unrecognized command

So I added COREDX_TOP\host\COREDX_HOST\bin to PATH and I got past that issue.

But now it is failing to link when compiling the 'example_interfaces' package. It's another linking issue, which I'm not sure how to address.

**Comment by ClarkTucker** [comment]
Yes, we're working on updating the cmake files to include the proper flags for Windows DLL creation and utilization.  Also, we're looking into the failure to find coredx_cpp, it is probably something we can fix without requiring a manual modification to the env PATH, but that seems like a good workaround in the meantime.  And finally, we've run into the same linking issue you just reported.  Hope to have the repository fixed up for all those items in a day or two.

**Comment by ClarkTucker** [comment]
Sorry for the delay...

I've gotten a Windows build to run through to completion.  The repository has been updated....  It also did require changes to the CoreDX DDS header files for RPC-over-DDS, so a new version of CoreDX DDS is required (v4.0.14, it is available on the TwinOaksComputing.com website).

**Comment by SecretaryBirds** [comment]
Awesome. Tried it today and it worked.

I still had to do this: 

> So I added COREDX_TOP\host\COREDX_HOST\bin to PATH and I got past that issue

but otherwise it went smoothly.

Have the changesets to the package.xml files for the rmw_* repos been submitted as pull requests?

**Comment by nate-jackson** [comment]
We built on windows yesterday and still have to set that env var. Any chance this can be fixed?
